sprite $CloudSQL [256x256/16z] {
xC_10S4004Knn-m_iH40QD_F1hdSRMPcPcPcPln8Um_jFRJt4EyJxnFl4-yJxnFlit-wJxpF_ka--wVxx9_k4--pVxhF_ka--wVxnFlid-wpVxfFkx-_U9_z
qttsJ_U9zza_tMV_T9_zqttYVVPFzza_tMV_T9zud_tJVLxvNxavryNMOH062r_mtl-5p_tkhh9pXch2txMDFoSY1B64Bwur0V-n-6w0UVHHJkKV1T-YZ4Fv
O-ahVaMDtO4JyJl-YdxW1WGB_-ymFuq_LFXJnAQ1a_X7mplHXfnVZzyDxuPrxGReyRtWQHI_C_-e815sBpm1ls4fsW4R812-E0r8yRdmzMb0oS-5hqy3Kdmk
V7qQU1M-6ow5-HtunwBm1IKnzFYZaNDic2Ak99RpTn0ydXkwcZzM-7EE7rMN1fJyOxdKzw9A0phyiNLTTuZIWEpi6m7QB15CTGL8ZbF6jbn4_8fCOqxIfN9X
-iEqvJfPpnz_fwdFlrO5AvFnS-6JDA3c3owrpDUgfk2bIGh__tcWROAroVdhphVhA_X3dpLjR5MF9bYS-11rw_Jh-UERBMrT_lhLAPfjvelfFpy_gVp9xL-_
F5cpjIu9NxK-FJ_GgF3r_5AtnNn1-De5YjscCeZm1VonVf_jkJkDUI6XVg3Mx9uRWFqLbhXes84tWBsyPYGY47yPR6sRWeBmAsOUMfFDGin1y1LfG2dyEGX_
Sl-N1y7Fxl_p8FmY6vWRP87yRvBOd__Hh2kClvCqi2dyFeBumpRM_6eQUFXLpyOFb75v_dE-TFmjLposxUi5uJSWAp-CfG4kV4DYVg2GD424Nu34_8-Vtjgo
y2kGcvzpyNtApm_hvCcOw2Gt_umtbyGaJwRcvvTt8-LoMdvUrv0wAJa_hsj9dNmZ_iUdkX7XtuiVQBHTTbj-tjVeW9eVKlxhyvykwd-SEl_heWROgVFV8nS_
1-exFadBs02lgxxMA89Ug9wVSwtjqyXhW3c_hflE1D7pSpoLyBa1BaW3PvaW8Fo2CG2PyQyV0A6tDwNnhn-0wZGDR0dVHp9-5Fyu_syKUB81oBdZTTt_gm0y
u_nhkpG6q1N-bsR0sdnYsHL-ZFy50VzZ9UyA7o9-H1sWhQG1Uhbuid-08OAUWgIBTFmieSzHTVwNOCQSwff_88mVEdwI1eZmnVm8FORrLV-l6oBv8U7d3tIZ
JixezBYevKVqGUhyP5pct1ZBZsUXzh_wB8hRylE6dXl2-L___fSoBhIB_KxllwchVK8zF-xjVntp_YlpJPz0m2z-_zbO_sIw5-2jdrMf0tJQ-m_xqaS-jtSN
XGu4K104wuD_pP4Gffrk1tLTUFDQFaTz_zNzqmkRld_R_MC-uF-txp-0Vk_xh-_tt_7-wxryZhP_qFx5bKtldxH_m-i_2Vl_h06iwVshziyuolxTPyu__hti
s4Fxb-sVjd_R_dF-wzlcvpVE9_yqdsr-Vjly_CRvv9_ciytFRvkVtpYV_DDyjldvRVFp6-UJVvhFDZ-_RNv-utpoJ_FPvkUtpSzldCysFxzjVdxZVBRv-Otp
6USppcUSZsqznldOreEFnrTLLLLLLTK9
}

skinparam storage<<CloudSQL>> {
  BackgroundColor White
  Shadowing false
}

!define CLOUDSQL(alias) PUML_ENTITY(storage,GCP_COLOR,CloudSQL{scale=GCP_SCALE},alias,CloudSQL)

!definelong CLOUDSQL(alias,label,e_type="storage",e_color="#2F74B8",e_stereo="CloudSQL",e_sprite="CloudSQL",e_scale="0.3")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo,e_scale)
!enddefinelong
