sprite $CloudFlare [360x120/16z] {
xDe7JZGn44JXijts7u7xdvQSUv4iXYw5UUy8dwngsDsRfsXz2f4wOuCro0Pgb0tKA1kaKJP0e-oGXjaX3RC56cK7DCmMQ9Wjq31Re65sGDFoGCDiWARbSORP
0KtB0KtBumop0vgM0vgMnPbM0JGbbcLmvkaMEDD5cbK0ZN9nDxGSmRmymUm9PaSucveIp8Q6f1uFuLnPargy2-QIvkjphgJ6kKkA5Cu_dPBpgQITLx15r4jp
1JMY61hdcMRZNDBEAzZYlD3EAzYZ61hdIBDH0OrpIyu5q3WFvNdEeNomgItdmFXOxRJEordNKr48ZV8QsdOEb0-_PgdNESFSz5OKGSCSUglgGSCykrGA3NDM
hlZR3kReJHThOyFvFCppG-ErVg7scdPhZ_K-ilgPc4F6JkpSSVQCypWu3llZaVUQ6xWxvp7wrxXfat4-qf1oFL8u7wrbvQrWFWJT8d0kQUfT8t2kgkkrs0_c
xp_emBcon8npvIKCXpFEm-6CSmk7Cyw1i-LNeZXxVYMAi-N7vJXRPcFWNDsqp0RERUiz-vtz4H4H4H4H4H7zU-ckNJl9KXY6eIYwW3VG_dTRm-hu1x_8rg7J
aFp8ygM7Y4Cg-FDOZWFtboFKdf7pGcgOXQnrpZsyyxyQS5Q6RXW0Sb8wvnvzPpZeB1v_AKcedmTpK3gBURmpF9OptZddehEVf-_CWBDwWVBER1YQLDkSEUFC
HMUqCxcMXoRNDcVEEtF0kO2FC-UTwp_plxEMXbxguPt3esrDSR_plxnSAg0Avz33ESVKg3DtstZdV9vm5ZsqSu3UwOnshhPpk54uXnvDvvfqfk4SE-LnBZhN
NcUzDQv-XQrbPzhEeQuwruiv1-QFi_cf8CT9vPq_pZNb_77sFwGylZCFu9nxY91odlzSHyW4PoQSlU5ZVq_npXnoHZY7n8D_xuR8FFQzUzvv_dSa80WE_ev4
hj16lsxu1TNnZBEqCnUIsseuPsX2ZJgBWUQTvSkyThORCm5Fw4DzPthEUEUOsvp8AJ7DVkSodv7KtbcRIUwziP80skNCDUTgE8lhP6ocyOjlpFITy_d6cPFN
VQbKyv-Y7Eax4vtpwqk05ivX4UUSUyXKME51dEkYynS
}

skinparam node<<CloudFlare>> {
    BackgroundColor White
}

!define CLOUDFLARE(alias) PUML_ENTITY(cloud,#F58536,CloudFlare{scale=GCP_SCALE},alias,CloudFlare)

!definelong CLOUDFLARE(alias,label,e_type="node",e_color="#F58536",e_stereo="CloudFlare",e_sprite="CloudFlare",e_scale="0.3")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo,e_scale)
!enddefinelong
