sprite $PostgreSQLinstance [225x225/16z] {
x5Y9WhCi35m212RHzltVzbyrYdOLfMl_Uxxxe33CC4dsQmV_ut_yZ_z1HDw70TuJEVUl8UOeS094jUkwVa3NgOeWSw1_EarYV7DwF8_GAxB_CqWwHpGQft6P
vmpj-iSt1bsG4ySlWq_TyngwxE_YiUEUhFtBTeeKlNDrikIJ7YdpqCnuF5lmoBUxbNn4LzjISlG7krAqypTXr7d4xc9bEfAY7HIIFY-W5mxU_M3Njp7hEncy
6-CKeJw4oCnPkXUYtKtlqLr-7KOonKL95xXh4Qz32c7V28x81zwwwF4hYhOqv1q1XemOmkB0N9saSMVYxfLzJeb7f0pTaE_1_hJUEVAicmyClrCnOCEYLyH0
ReqG4tRoezSKDye_XCdz36DYz2ExwwdXxDwMlFc5YDZSS72rJMiPr35L7q6pqtpk2yNqheZyA4cUdBloMgNh7pyCc-Yjsnr00tQtTh7uHlrR6-Jlmvbs3HyG
4pQbKg9hv3M4IKg0V4DLHO2SKmpUkHUAib3aTdv1R6sp08x2KjL_Pe0hs5iR4aPUOe0OJrL1YXQnHSMd0QqkcPVshtsHipRVYjH13qE1zVLk1cbYJ0RcE1oN
NbqUiwe0ClzOCnrePmvKSfwuNwwogK3C0QXXU-p8EMVC-mAZUpXk3bfguFfkXgMG0hKFM0vSrkL5EM3PHmhTpAjGyXWV-hSKBJPb4pwxrVt7B3zXkmAfCiqu
NyZ180N8x6dR_AW0a0ECPbrTo9AcepWjyPdMUzf-nzkg8XKrLl19pf7ycc9Ismb5GOFz7eKYFGtfQhxqOtpseSnfqXMz3aGqajR451J7LQ4gJ2lD8IhLXOgm
l2YP7NUjYEgKddxUZ4KldB0adkJW5cCdh1UZjdf3aNZ_BdN-tn19zEAvnnM6X1K_Doa0kGv0D3dZ5zlMALAX671acfAgqHNNVVExub8ND_vqdAMHO172iK3Q
01GLAMjvTVj08hEfxo-wr4zYHpjYiZjimQm2vMPseX0iiZW-lLlDmQ8pc4lFgeMCIcVR8PiR6g1p7lgiWbQ2efQe4ybuuTd7sQLMBUeLFqt_QUQ7IZhKmwsT
Nwbo45wAtE7-nLVpYu_6qDLUuAIpUInBEzGIr4C1UGFMj7mPudHFXqcZ4Crkew5M2ERoKDqNwtIVa0ROPZITIj7CpG1QHh_g0WWWYQR4vxFPmaqDjlaVWlOd
w1RnOMlRW6Br2mp5RC9kFQ5tL1UGxJyh12qdWq3jnRFy7eY58RIQ19WjJLBjsPoE5gOvm9hzfObAZVurmFFRWcPKBG6OBUF3AEmYF8g0ljbXK15VgiiTM1YA
e5wF8QQtr4e5LWPEey6b3SdTPb21h7g-g4k_UWY_clHitGkeB_ubQKsOadnURe0rctF7mLhvVuPfnk-EFHf7TIUfMJ7PekKyN2-VxG0wDeRvRAI1-kBHfz__
CjetPEJkf5K-YC3RWxd9eUFtUM3mwUmyo2kFnZs7Qkd6Wq8Q0Krkxi-1EnZgT6-X3CuLZX39D9Wq71QAO0vzssM-T8-G6s4Cu-cz-TAioD5NclhYq5RaMK10
xWJcxe_rqarCbV1dZ3eKva6b7T4Yz6Q2MAeFGN3X15rfDzUmVCtZ89OKqWfO_TIR7Gg1ybplKRq8NiMeEnZbuqWGqexqrH2_BS1YFfSLLQLBk_AatOonloTf
XxNPqJfqt2gXm6f5tLbvDJ7GViOytgzapkhn1r1Cod9ECErMUYFUjmyI1bZ4u5QFsYSfvZR-9CTh1BM4Q99Me9iTAXz2TgiE16XNq5c8laTGr5iH_1ZYTX9h
9sYpOEj3mlXTpQ6GZm5a4fu5UTudIEDVXtQ2wqeLv8FWKmbJBKMfy2QqAnWiv3w8ys65QtNGbx_sqWxwy1CiTTpb4uAwtyc4yjV-dOpx-1CKjL8HKIVOxtzv
E_w6e6PppsUHJf8ibccYFo3u1-tMWUuu2yH2HqoIlVzf__A28-B0UiRhdQsl-RDic289zhGsWB6BGJseEVEVFsHd-aPmwvsESHwKswK0-wNpGiix1q_awoUP
gwS0FRCb9gteQO3OSinU2yO5hn3xXdUjEy8ncPHB0VPBUn3Fy2Rn9_3muQov_xOQOG2IhboYs9BeuFEGlU9tDgIXbfnpIZddyW8OZkjyl7OFbk-zKL-sv9HA
1IbDw-94_RIdkVLC0Ka3Tn-k0qYk8BrlgwJelNkx1rFb6xN4jx6eGyKKOAI0H05jLWUZ-KadLebxA_HqZVupUzIb0xUkcMrIzsl68fof4gvFMTbFtNqk2soA
h-IrrZulHJJCq6J72AjcMry6AnqWtylA9Msn04bE2q0XSpyLiJspgqF3gJfFU8J6JoNe469RzJJOfb9BBIMdvDO0nraYhlmLFTCQ0IBmLT6P75Ck9ISw9REX
j1UUIO68o4_X4P54WFDsiVrqec42y35mCbQ0_jlKZ7V3XSqOw_Kb7-7jn1JfRX5mxbnCREiSm_JQ7_KPW4INqUdjpTYx2KJIO9hU8veWfnX2gAz-8IphO7NK
wAjREIoUfyIpEhYeGmOpHIq5FoWxGYqBYj3nyVMxD71RqwGxC4vvRMDsVD8cWBJEieaimVdWNIXjE_ANvHZTbX3TpLLfTUUkT4k0aQzfxa680-i4cEfyTMzu
0uBiIYiLDRcu5JLdaW7YwtyzgZHizBAijc0GUbtdXJ3tEc46wBxgG4wbsxrz57ZBXMCNglgpe--mBgd3EdWgsznZCJA_SYB9X8-U6b9y3Z-b8vK0IPPAmPqc
9Onhe-nMEhTxSjndSrEiQwmJIM07w3_7URGKIdJEfUopSE0u20pNUzdvSeofChlkcNTWU2QW3BymMGZNm0c0kqakXbHIJZwITpC03403TWF3fCvZk8K7PVZl
o9mpl0rWcwgA5P9323vaQTZk09Obl_TleLU92S12ke86XBKFo3LRp388NZM-0W8M-se5EEOjo8n-nP2MoCSSMF5EDTlx5IhOOD9QNNG0tROYC6urj4wCOjxQ
EM6fMng1S4Paw9gD71lrecXufZwrOQwFfOaHtWrdVDO7Mbb3uiK0cMLKXNKXSiaK89T79YKwZS8km5yF40PP8CshiHG2dBdanXMwpZBCnDS2RFeqAeMEZSdd
ynwWr765kYN0y21bMgu76DJYgcpBUGym4-1Yac2HM6OPBeEB0KPAYD1r3dNUX9U5sVT1rcKHe64qd06esLYP00ylc9K0g-Eqy6GRiyeohujV3p0h0OAsAGL0
D6mTwlEtAvJpVXok0eiyM0py_Zh0bEiXnsyGxUvkxZY7CijaUwbN0JIfmBJT702aXUN9AZSBMYsXAlNs15aDrwNKUPn5XNqewQP5WDE6zc08_Wv0t6RTsgGE
Gk3OXpwJvlpyThim0eG2e3ez-mcMMIyAoOipFMjUXldyKe1GMKtmqRJuNSASBTomEnZ8MD7Ru7DI0GGk1WYUqwip0OdFWGj3VWr7gzVnOjqihXvm6ZluFWD0
gY_ni-di2lO8C0to9htswqtuv2RKsGT8HuWAeCrRT4E7rYaBVgvFqzKhpWrEoT5RiNeG10g0KGiGWJjbGJg1xgTdNw67CJJaoGWmoeLbWW8CQ4I1y5mE9Ycc
tOv3AC44ux71f1losebNY0rWtijxvQMoZeE4fH8gGy5QimsnsYUfAhBIynEHTpqxxR9IijanMAG4ZQAY1uXDTan2ThIIU0Stn-sXIp6iX7UUdDK3hDgEN6-_
wTOq0WJrowyQySkf0BRd-tkz5Y2Jjsf0q2UlxHL2sXHWVyTtEYYF8mxR5Q9wq9P6nklX0PAsH0fCg3b8vYtJfNqGuScUBWiC05MfDlpRtfMeFOwZGACRK9Bt
VzezuYwB_74IhDsPYVlhwhl_io8948P2Zc2SGc1y4hDrd57CSp52F4gGvJKoVCdHbYMaizWGj6yDKC1neffgFN70Ip1EDTK4b0S-4yGRsmq1j0_94QrD46Gw
z70Sddsq4ZmHX9-y758tn0SmeYyFaecf_2adrwr20yeEh96n2rYnWCT4HRlBCleTFKAEmpr35GMKbg1Tm0vLF3UoRJTNVzL7KH5sFIFrKrIHPAxspEP22EqA
h8SRgO-u9wcduR7Gcq9XjYtQ4ytFRJ5FOjemnGKB2BVc1Seju9ST11jzV70KfcoeANIBF1n3KHPE43aQPGV774KoUvJVjn0Z2bF-qA8z9O7KQEkxxH7bdhWj
JYmW7jRZ6PtZMG8U9RmkFWiufHC4DMtIJafudTYQqEjH3Tl-NuRsWIMxpabe-ihU8xyo0QHTA2DF4pVz7xhEB20It0UUvmbYnXSBc6PxeiIKDmV6Jb7SCtXg
0N6_Ek2Q5JUtVGOyh_HaO-wo_abL9I551dcA8y3A2v6t-0hQT8NV7D70K-H6hYbM74PiUToJ3iFA1bNvtBQYq42hGx3EODDXqJc626GNdCM8g1bHwDmUBLw1
ICQtWFMsz5ZgkwOuVvC1q20z9BCowMWJxKF5XVb3WgXNMxUgzesIy9PvWc9qfnKcpR60lZtwEONFh9hG7B5AFZvP-OPGTKQFKpSQr3JR84t213riRtPRTnPc
MW-9wNEr5ZP2Wsfo6R4HapQoFZulSxYCiZPYnn7SWgU5Cki3aGZUymHr2zYeS48z0UwjKx1zb5a_46GMrQ4ccPex4lVtO4DVBMMoGfjnZXvygE1OknxBSXhY
mpPZFygo9W2VmumE4UiY-A7XPfqH4CbjPd0DOMzZN3PQxYhhsYPREQYJRTXisazihZTW75GR0sGwHx-UVt6s-c2h5ZiZHNMehM4nPWYohSks9-XsPL5z6b9o
TIKmOiSUFNAFgp_6DJKksENJ_F2JfOpiDBZSzk5WICrOuUnqM2-xKekiVShpdb2amTVIQkE1MORvEaun-GLTzn5ZJBcqUOB2oYNHk97lp89IOMQzUIFmW3ud
xpCXhOY6StX1iqnlKXNxIKlJwmCrRh2U6Ch4NZDJtM9Dc0wJBpSjBmnPuaahqs2WpNIMSk_hBP0I09BLI_zSUwXEhHyU_335ZFRsnTGAggJTGNNx91Hxr1Tn
ftkC6N-bONdNFOpCxfqVvf89jsfr6ZRrIZuchMjYxGCUpXjnAwwhhz9FpAFt50OSs9uPKAIL8HMUsAE8ObBZJBxRh2SALxmdqkMVHXIyv9U7B7WuFA5ZMy0i
Aghx56aXDBIZzDUzX2E-v5TcF1lBQv5nnz4XAPs5XMVkIdaRIL7JDX4j4175N2h3IyK39Gdh89Notf2ou1Mc5_oYQEDDKZhm8OAsWfiPbqrjTmjQ_uFLZVIM
o9gExi_DeC2cl2_te6NX_N0YD5tjauOPXMGusCIg-XpmgOeH2Q6b7Sfag7ddqDxsgI021l1XHAqp8_qtqo4CkHgrvDWQEHspCiiu_FubxFJSImImjh333vbn
Qtzr52hneTiyNXU6ss2sKO0nErJ7uN0XgDrhJSVTPKoNinDNW6lVt7pPBgqiZkeKRn4O8ociPi8XjJ6qpObaLoECp1Z-K3Z0P293A-MJUTrPhACUJsM28DKd
eJLLuHmVOw_3gJQ-cjnEUXO3opR5ST5MuaFaaeOc5wiG2Cv8fQVAOi3SIWwFppN1pv3sHQGOrqJvvqsq69K1iU4dZVStjOzp12EYePHpoIiGO0CXzHb-eyuc
R68SpBgvwa9mWDTB2S_pBaKP0mhlqG3D4VJCLxrDJij41fa9Db6t8wxWrtw9y13POPULZS43lyC4MJwUA4gjZxcyD3cjjWx54PZH6eRlYGlPZPrhur4jFshL
PWXo-304NgvRWkQI9uQrwuDheQ8hGxKZkMIXyGKhyoinzoc2z6xj1AOJvdC2jnM85b9RfoXY3nls8JDYfm7MBHYOA2PXTE33dOz4h_oykwHb3l3XP0vO8Cll
1aVPhHFXdqEmQAfQfj8OXw4g8YF9Qt4fjCm2UTRmd2G8oA73S3OedpuB55AS8bW8tyCRAEZDWL_i0S9eoh6wTvatNgENLckAuosDQOPWNZuHlCeqlL7UTTsP
74xrkkTzY4A8_mNsCKO2wzGA9dGdlMGNv-a1GPwt0kLkSkSjxEUvQ3E-sCXrIZcnFx8QO-y3JTEp21sVMbkEH24X-GheEnSKxnPFvWa6yDhkAr8TJygS8ClG
VYMdcKuAKpH1aCCMpSj2lxQ-OzKcBSqpDARXQt6r7g3Oy6fC4KJNcZyFCO_ITuvu2nX-ZdNaUpOzK8Wn5m7vCn1SOlj1yQAPp1wqnAzODmT1hv_For-EMDIG
u4Ju_tfpO8fW6MumBNy3A9QclNU64HjkxXsqprhHF2B--3VGWoidsjd0brVq98KsIp2Djh-m_DD8TOUZtk_wTPAWdK50_p0zsceFHBNthi8rGq_yn0JzjVmw
CgK7AxRJznCiSmJH2t8gWdg4O3NIjgSXUDmDectpIu5DrYS6fELHtgdd9EWVxCcd8SXpNgBzZWGvM866RqQwuc5uEaJGKHboQe9sYaJwReANJT5C3y_BuHCG
ZFyb60yJj1FfudSJxD0V27hOItHKa7ynGaVVBEbXBx7wUVfkWeeAwKC4WrKGEGd1vGX1CmUaBDyDthv74NOtJ9p0Im1jYqN4ZsOLKav0i1tinhR3b7huSeBL
dHZT7zZ6zEK42mWUkF4gnaXWUtzxC2e7BuICIIwmmDyUgwbVXuU7H6KPBIhV7ihqS8nW7KPKwTi9acxw4KvjNMKpiAqkNm_POZK-Daocd-08OgTLlv8IipPO
f-_tWaY_DtTMXaSH-maYxKq311ECF0ILQTIDf-K4q6ssOzK3CzxGk_7zAARjsJ_rZyzXGv7TP7ABvrZ9W-KSK5ITGevHTzlrc4qzU8E9EGFgMC9wjvFjkLK7
3LXC2stPYd0IWc5yin6JmtRMpWvEbVCi8BvTWIoBikWhWHpmA-YTEWdoS6bKLNYN7wFXaeOq_Lb0zx0IWXvF2uZ9nE6XXfEN4y66NLHuv_or76Zhs4QZ-taG
kesxOcExTCgj1395jEXyEziIZc7S56fZqRM7-KV3LOPuxxaGPTG6WoHgUFUAn0kTYn_Iy9T47yHUhlUwwRQS3kXZhFHAZO82ezusduyUGRBlrlEooouhojxH
E7WwXlghR5zoW0lOMZpbOZi1Juh08D7REau_XfHobNu3i7mdHMWFBUcg_QUqbYHQpeoGm6SFLuwqd1sXNLzqqFGCTYT7g1tqZFhKxy8ExPIisY-NI-yYhIGe
YlnE226cb7wq6jBfEOB67_p17_mR
}

skinparam database<<PostgreSQLinstance>> {
  BackgroundColor White
}

!define POSTGRESQLINSTANCE(alias) PUML_ENTITY(database,#2F74B8,PostgreSQLinstance{scale=GCP_SCALE},alias,PostgreSQLinstance)

!definelong POSTGRESQLINSTANCE(alias,label,e_type="database",e_color="#2F74B8",e_stereo="PostgreSQLinstance",e_sprite="PostgreSQLinstance"e_scale="0.3")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo,e_scale)
!enddefinelong
