sprite $GoogleCloudPlatform [940x120/16z] {
xDa5gWGm38R1f-cYlVzfrzqrD31pXuy_j5zZ0W0000000000Y6TzvGAfjgTarWf4jAUD7Yj8TIshLI1Q6pzM8Agq2cQrJgnWLYi-Bu5Kwmyhk83pOmMYIgjW
LiUF5OWghO9PhHGhcDNw_pOWrVnXxJjVQ-027YpMVaIm4EErsjVoSgr_2M1MysFjLsdr06PrygpskLBNjBe7i_hpVTD_E-zpfQvfTGkfpjYxioq5cHuAmn7i
wMZV_zN-upVraa1UunOBoM5tf2JBny8AbX-NxPYIYRM1LRLuLwktHJZZN5YQBeMuFlWgMFLuFwkrCe3XxKKed4GXzRm4sfXMhvTAJ5yFdLX5uhsiAetHhERH
iDejwCZJwkTqASNyo8bLB0vgbLTcAAlyJFnIDVIqEbzgCNq2h9rhlBUULxKLHx6g9rcL3ZIj9ZGToqjbZU_wULM56CSgFnC_LOtThod7HuBLKZzUtV6jgXJ3
MELdSb95_Hh_n5eit_lrR5ICKQpoCsayWM953zMlyVTjoiKxwBqGV0v8_d5QnLPZX9X1lyRRjm75E-mzXhmk-XLZMTq-JR_L62UcwGhwDRXlusfsATx6wcPP
HhQQdud1gfkgt-hy2VernhuDkoHv6wla4xnYRAlnBAkZKfsle5_3bvTQhydJQgqgWwujRPJkjFhRwZpFqoTTME9zc_wByhIwcHRZMutdM1rqMlrlrFeryMSu
bfTqMcqTIb8SmMgSLbUfJX-5QJL-1UlRzAVLqsg0EApLq-eyR_PhRXwA9rR--ZwjSghZMutJwYhL-RhHhuc5U6ZVHgTLXkxuLdLQNRGwVwxsQo9AM1jz6tdl
zV5bKwji88TLynVsF5PHaRdLVfcIr6e_kK9rOMBzc6fK8nfz6_Fj0xV1iWMoyyLBILiZ8NDzg_Kj9Jf7DLWbvw4irlxNgbCooCAXyZ6AL7_tRSfKez6tSLhL
SlYoYrR1G1whMeg-LTs4mIeuZvvLNYSfjqg-Z5srEi_vmbAaqLXUybq2AmrRTicgaW3aUbRHHWpDephNWRKSp2gddbbTUvlIGkI3LAdE7_cqcaUZR-DRZScZ
cHrgM0NZMAmgZuvL9M6pgZGUOPNNIIjMwTEeMftpQPLCh01htohMrCeEDQo2SInMjHRGAYX9zxubLCUELLod92f5oHEALEVhShycYDNBRB0AL85N3iuEDQo2
SN8tt2gh7xUgbxAgXbLUfpn1XK1Mvvlu1FqQtBVnMjLTBnsOtR2gZIY8irhLVLRLjBf9DU2RSTUgThQgR5fTc5W_BbshqzvMQRbvDhUgpJ1RbIJsn_PHBT-9
owR2lbLOfW0lmyr6ufRL-JQcZwy9MwtsRSnMwpNQw6y9fGEh-KX-gvLBXOxLt-d8AdWwbHNsnhqGe4mR9rbyjw_U4p4lnlN2hLRxDbwhQVdoVy3i9BrWjJII
rMew3h2AZyhtMo9MamCsh88o9US8pAV_ALkzDAtcdrX_lfziTRLw85k5R68rUQZLQgrfrR2QP3hsHjlIqR2gKfrGigfrMIlNTLwAYLijhWJ_XDsg9FBgQMH3
gpNc-rWDO9KTrRS_SCAZOHMLYIINoyAjpbFRwlJr2bPN7q-OIDjF45XD7kUrkbxRdjNyg4_UTxzb5PtGqwt6rMJrkaprkLQtHY3P0hA1LTs4t-f6PL_6QknY
bNNGL2eK_qzq9bOwhGAgYGs3rG8WdisjhfwEtof9RX_LyDjJsJ4UR3LsjGgmiearwTWmgoa6z22WFG7Ka9rQ1NT6sAt645QNKxSEuBSQorPZHwjJo-gKKJLR
3MIrCXwGpQo26vVwLalaBLRZBgi0LH9zguMYWgDZgww9jT2luLRbiHhxMmLI2nnUnEfZzd01Hz41h0QrMbrUgbET0LMVrGVB5iXUjmgWxc5L8rYLZcxLSnLS
xTVyX0Mh7c8rzhKQ0QoULcMpgfUqolisddxDQRLyWgVLqse7wmKiB36hmbI7l0Ocvawhu4iGHxBAbvSkYLJShycZPNM0jQL4Ah1whYsbzJlKvrMul0H_8uDF
g_s9LIDRxMwxVrhD4iUtIg-2mMzFWNuDm4gf3d0l18J7iVPLvOxulH1Ugt5WgtHvYSSCgFQnQisgc3wprG1GErQbXgh1h8R1AZYXNQrohAnVmwsAK8Ltunko
yNVYEDP2vd6jLgVLyQqQ9bRQh-5O1LHlazZ_Et7vKBMIL6eNN9MgoKBVix5Q3QjL3MMLOvq0LO0LK4r8UBzhthSgFGHhnWYeYdkjQd-hwba5PV9RvLYXrK-7
LQcIb9WPOG-N27ODKKZgxWjHA24wwlvMPTWNmciLzsqSqoh7Af3meBtH0cO3g-JbaGnSIX5kTKZWTwlWVal-jIKrhO8JybjrNmLt5vRGjgivcm9AWMpmvymc
U0QraXGI6liO5hOA14TzKiz6wbg5PV9RvSjB_NuD3x40ZzrbB-_wW-6d-DgRHGej_pEuPCaAPREABgSa80FKQMUh02lhrxYnyiVUdHsxMOt2E1lNYij9szR0
2a6Iwx6QZxTIjbm6AvFVAiTgwDS0h8Zg2ByznQdoagGO7leM1bADz-xp4ybbW3AzfjMflx3arTh-JKU_LV34-XLPm-1v2pk8LLWclrMEjTklyM8r_5QoyVTN
eq4Lgw3JPMse04SrMGqq7B3AokItolistMdLgPK_KktiQ5Y5G_6Xjp1qtvFOHcNXiHfeEB2TFoYJsMhtAjZVhy5J7d-aBJjogvMX7bAH3GpiJ9Ei-b6DUwE1
zv48O9MKoM-LOvrw2qishVSyqfSTLQlHe8gqaS_du0woyb73P9K_Ds0LbEaLhSxJPYnJ_GPKEJh-G3WCoVxz5_p4Q3ImepDjr2_iSUSRjw5CXW1OONIlWFqx
cS1HI3PuEO0dPge8FzD6HUpXHxIRKx2yXE83K3rk_BkTkpPm80QWAAX06Ad_Qe-IOpC8Pdfu_bxI8t-08Ouwgrg5wuSrRvPgxrEcYc6DMyrg_p1sguZLF-2J
NduAGqAhgVwfBLhg-AqYLhFQlnWuLTnUScFff1V4mmWmh6ui7JyVvkamh9xNzEF2Y32iiUxLQXWgLOXJt5ZIAaJFQ_urIQg8rOl08wKACRgnzA_fKaMiiVoT
QWkBcwnKn9h_BhM5zOsJAiIZScr_2NkO9rJWn4u100000000081N
}


skinparam cloud<<GoogleCloudPlatform>> {
    BorderColor GCP_COLOR
}


!define GOOGLECLOUDPLATFORM(alias) PUML_ENTITY(cloud,GCP_COLOR,GoogleCloudPlatform{scale=GCP_SCALE},alias,GoogleCloudPlatform)

!definelong GOOGLECLOUDPLATFORM(alias,label,e_type="cloud",e_color="GCP_COLOR",e_stereo="GoogleCloudPlatform",e_sprite="GoogleCloudPlatform{scale=GCP_SCALE}")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo)
!enddefinelong
