sprite $Kubernetes [256x256/16z] {
xC_10S4004Knn-m_iH40QD_F1hdSRMPcPcPcPln8Um_jFRJt4EyJxnFl4-yJxnFlit-wJxpF_ka--wVxx9_k4--pVxhF_ka--wVxnFlid-wpVxfFkx-_U9_z
qttsJ_U9zza_tMV_T9_zqttYVVPFzza_tMV_T9zud_rVS6NlFjJa1c4W00_5IE__mka9sTpa0tmU5XUbvxRzh2MyPoExEafnTQphjmG0oPRrQ_KPlo9hHs1D
_nRm9y8czI_8Bn4l4Sjw0w1E_1hgCh2OFuD6NiklJ7mUOLjf0BI9poFQClufYJ-j3Ap1p-Y8V5L_2UYAe9WBtywt-14Qwk_oCl1UlsMseSSVM6TVCw5_Fd-Z
fVwNdsuRsDuv0CB4hpbU_SvlyZQ_VCxRt5_zxfjyBaHlw1FVF_hTaw0ClDk_qUBE_MvHkqiydLyYpshkvsKWbja3e4pyxCxyDRAo3AZvJObxoy_BmCm1aCrv
qRp7xnPbSw6MtoPmV__WwGT0cVXjlxuC2FtjrzxlTnEL0IM_FOLnFu-YAGDQVtiNXllxTvwaVkNExhZV9P-CTNvUjiVy-hbGnhV0N-f-Fn_KOA81EBhkvxxl
Ycp7FcuxHFw8bqZDREdUeXDU8chyXrRMQ2CJHMhU-aY_o_sX7BrDbw3s-sTZ8F73ZeD_-JY_A_ZUoxUux-1VleO_uR-HPlcTy_N-Yk2H9_bTwzz_232Kj_XT
x-U9pyk0tk_p_GcTaQRxNU_F68YizplXw_mMC1J1hkNtXA58BlTxvIlzlFYrIw3UxpA_uFmNeT-L_ltdF-dzFiblkRyCfCgrENwN-mj2wJp_iTukeCZzFiiF
H1iv_zKYCCdlS_n0wZ__EG5p_3xH3snaBYHptWRCy_j4Fq8XSo7voXNz_5rcMyPClq_pyomdbU6YVbxboSnmLJ-VvScUmSNz_7Y79U0-VY0ps_Nz_5DU2RYT
7uXMo-3j_7NQtu2x-dDbpVO__iV_-1y_xkt7xVsuh__np_Z-_-FF-_nPxfzo_Az4xFCZblFxBG5x_K2I-lN7_pcE-tbadHzoVmduh1-XwFsG-2t-9GrZ_b3_
5z4aVlNvN-dLcRly_0xfV7xo_gLUVoBRp-5-wVcV9P3yhI3YPuV8NX_cFEU_flWFaO28lmuNdJzYKleXUCWwVnCGz-V6YND7-I7srosPWxW_EGcB2hzW07hF
v2wH-wCvZnAEzklNFo6trhzKVtlzIpwRFpHkcr_zxIL3WVWNMm0NnjQ_LV_eQhbmaVMFl_pprpzg1Y2Fjl3QjlhxIFEmBE2BrZyB-Ya8Dd_b-lVZ-ocOZ0z8
-n-C1t-yzVo25bxo_XSyDFrF1Ct3pjN_neT3rVz6C022rqx7KChNzx-IJoJw1c0Imbhzpm1v_pjzuklz0eaWyGKDC0LbG9luDLRfVof8V7q3MFqkR1RtWb-h
_t6DMVsF5-j_tRx9PHgWypUtkObSny-JMv3ukWiWg3uPyob2ojVx-oVtVNEUteyxNVz4x-zV_t_j2m2vhNtz8_q0r38WJ_mQp_NFbXe0JopnPV5S__2v_kKQ
Vbu6ialZkVxj_d1nbF9S_tfbF-xDV_ouEHzu_1VbNty0yBNzEI50802084J_r8Rm_XqQqFy8s_t-nllqd-wptUzlkz_VU9_-qtss-_rjz_iRxzD_kizslx_j
Vd_ZVVfFzzdkzxVTxs-yptQ_l-r-V-DzjllzZVSPxpFUPxoFxJt6-zZUWyVdaoH9aYG_
}

skinparam node<<Kubernetes>> {
  BackgroundColor White
}

!define KUBERNETES(alias) PUML_ENTITY(node,GCP_COLOR,Kubernetes{scale=GCP_SCALE},alias,Kubernetes)

!definelong KUBERNETES(alias,label,e_type="node",e_color="GCP_COLOR",e_stereo="Kubernetes",e_sprite="Kubernetes",e_scale="0.3")
PUML_ENTITY(e_type,e_color,e_sprite,label,alias,e_stereo,e_scale)
!enddefinelong
